services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
